import type { Metadata } from "next";
import "./globals.css";
import { fontMaru, fontMaruOblique, fontDisplay } from "./fonts";
import { ScrollToTop } from "@/components/landing/ui/scroll-to-top";
import {
  getSiteSettings,
  type TextMetricsSettings,
  type TypographySettings,
  type TypographyViewportProfileKey,
  type ZoomSettings,
} from "@/lib/api-public";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Pre-paint script — emitted only when admin enables `Prevent initial
 * flicker` in Settings. Synchronously, in <head>, before first paint:
 *
 *   1. when `normalizeViewport=true` AND `normalizeViewportWidth` is set,
 *      writes <meta viewport content="width=N">;
 *   2. when `enableZoom !== false`, computes CSS `zoom` for .landing-stack
 *      and injects <style id="landing-zoom-pre"> with that value;
 *   3. when `hideScrollbar=true`, adds .hide-scrollbar to <html>.
 *
 * pre-paint script and LandingZoom intentionally use the same viewport basis:
 * `window.innerWidth`, then `documentElement.clientWidth`, then configured
 * fallbacks. Keeping both calculations aligned avoids an iPad/Safari scale
 * jump between first paint and hydration.
 *
 * No hardcoded fallback values: if a required admin field is missing or
 * invalid, the corresponding operation is skipped entirely.
 */
function buildPrepaintScript(zoom: ZoomSettings): string | null {
  const isPosNum = (v: unknown): v is number =>
    typeof v === "number" && isFinite(v) && v > 0;
  const resolveDesignWidth = (v: unknown) => isPosNum(v) ? Math.max(1440, v) : null;

  const enableZoom = zoom.enableZoom !== false;
  const normalizeViewport = zoom.normalizeViewport === true;
  const hideScrollbar = zoom.hideScrollbar === true;

  // Fall back to 1440 (matching the CSS --landing-design-width default) so the
  // prepaint script can apply zoom even when the admin hasn't set designWidth.
  const designWidth = resolveDesignWidth(zoom.designWidth)
    ?? (zoom.enableZoom !== false ? 1440 : null);
  const zoomBreakpoint = isPosNum(zoom.zoomBreakpoint) ? zoom.zoomBreakpoint : null;
  const scale = isPosNum(zoom.scale) ? zoom.scale : null;
  const normalizeViewportWidth = isPosNum(zoom.normalizeViewportWidth)
    ? zoom.normalizeViewportWidth
    : null;

  const cfg = {
    enableZoom,
    normalizeViewport: normalizeViewport && normalizeViewportWidth != null,
    hideScrollbar,
    designWidth,
    zoomBreakpoint,
    scale,
    normalizeViewportWidth,
  };

  const noOp =
    !cfg.normalizeViewport &&
    !cfg.hideScrollbar &&
    !(cfg.enableZoom && cfg.designWidth != null);
  if (noOp) return null;

  const json = JSON.stringify(cfg).replace(/</g, "\\u003c");
  return `(function(){try{
  var s=${json};
  if(s.normalizeViewport){
    var m=document.querySelector('meta[name="viewport"]');
    if(!m){m=document.createElement('meta');m.name='viewport';document.head.appendChild(m);}
    m.content='width='+s.normalizeViewportWidth;
  }
  if(s.hideScrollbar){document.documentElement.classList.add('hide-scrollbar');}
  if(s.enableZoom&&s.designWidth){
    var basis=window.innerWidth||document.documentElement.clientWidth||(s.normalizeViewport?s.normalizeViewportWidth:0)||s.designWidth;
    if(s.zoomBreakpoint==null||basis>=s.zoomBreakpoint){
      var f=Math.min(1,basis/s.designWidth);
      if(s.scale)f*=s.scale;
      if(f>0&&f<0.999){
        var st=document.createElement('style');
        st.id='landing-zoom-pre';
        st.textContent='.landing-stack{zoom:'+f.toFixed(5)+'}';
        document.head.appendChild(st);
      }
    }
  }
}catch(e){}})()`;
}

function applyTextMetrics(
  style: Record<string, string>,
  prefix: string,
  metrics?: TextMetricsSettings,
) {
  if (!metrics) return;
  if (metrics.fontSize) style[`--${prefix}-font-size`] = metrics.fontSize;
  if (metrics.lineHeight) style[`--${prefix}-line-height`] = metrics.lineHeight;
  if (metrics.letterSpacing) style[`--${prefix}-letter-spacing`] = metrics.letterSpacing;
}

const TEXT_METRIC_CSS_FIELDS: {
  key: keyof Pick<
    TypographySettings,
    | "contentHeader"
    | "homepageHeader"
    | "subtitle"
    | "bodyText"
    | "sectionHeader"
    | "textHeader"
    | "promoHeader"
    | "teachersHeader"
    | "body"
    | "bodyItalic"
    | "heroTitle"
    | "nav"
    | "meta"
  >;
  prefix: string;
}[] = [
  { key: "contentHeader", prefix: "typo-content-header" },
  { key: "homepageHeader", prefix: "typo-homepage-header" },
  { key: "subtitle", prefix: "typo-subtitle" },
  { key: "bodyText", prefix: "typo-body-text" },
  { key: "sectionHeader", prefix: "typo-section-header" },
  { key: "textHeader", prefix: "typo-text-header" },
  { key: "promoHeader", prefix: "typo-promo-header" },
  { key: "teachersHeader", prefix: "typo-teachers-header" },
  { key: "body", prefix: "typo-body" },
  { key: "bodyItalic", prefix: "typo-body-italic" },
  { key: "heroTitle", prefix: "typo-hero-title" },
  { key: "nav", prefix: "typo-nav" },
  { key: "meta", prefix: "typo-meta" },
];

const TYPOGRAPHY_VIEWPORT_PROFILES: {
  key: TypographyViewportProfileKey;
  query: string;
}[] = [
  { key: "mobile", query: "(max-width: 767px)" },
  { key: "tablet", query: "(min-width: 768px) and (max-width: 1199px)" },
  { key: "ipadPro", query: "(min-width: 1200px) and (max-width: 1439px)" },
  { key: "desktop", query: "(min-width: 1440px)" },
];

function sanitizeCssValue(value: string): string | null {
  const trimmed = value.trim();
  if (!trimmed || /[{};<>]/.test(trimmed)) return null;
  return trimmed;
}

function buildTypographyViewportStyle(typography?: TypographySettings): string | null {
  const profiles = typography?.viewportProfiles;
  if (!profiles) return null;

  const chunks: string[] = [];

  for (const profile of TYPOGRAPHY_VIEWPORT_PROFILES) {
    const values = profiles[profile.key];
    if (!values) continue;

    const declarations: string[] = [];
    for (const field of TEXT_METRIC_CSS_FIELDS) {
      const metrics = values[field.key];
      const fontSize = metrics?.fontSize ? sanitizeCssValue(metrics.fontSize) : null;
      const lineHeight = metrics?.lineHeight ? sanitizeCssValue(metrics.lineHeight) : null;
      const letterSpacing = metrics?.letterSpacing ? sanitizeCssValue(metrics.letterSpacing) : null;

      if (fontSize) declarations.push(`--${field.prefix}-font-size:${fontSize}!important;`);
      if (lineHeight) declarations.push(`--${field.prefix}-line-height:${lineHeight}!important;`);
      if (letterSpacing) declarations.push(`--${field.prefix}-letter-spacing:${letterSpacing}!important;`);
    }

    if (declarations.length > 0) {
      chunks.push(`@media ${profile.query}{:root{${declarations.join("")}}}`);
    }
  }

  return chunks.length > 0 ? chunks.join("") : null;
}

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const settingsRes = await getSiteSettings();
  const data = settingsRes.ok ? settingsRes.data : undefined;
  const scrollToTop = data?.scrollToTop;
  const typography = data?.typography;
  const zoom = data?.zoom;
  const header = data?.header;

  // Default mode keeps the legacy "parent only" behavior — childless top
  // items show no underline. Only `'all'` or `'none'` materialize a
  // data-attribute override on <html>; for `'parent'` we leave it absent so
  // bare CSS rules (which already encode "parent only") apply unchanged.
  const navUnderlineMode =
    header?.navUnderlineMode === "all" || header?.navUnderlineMode === "none"
      ? header.navUnderlineMode
      : undefined;

  // Per-size override flags — each pair (toggle + value) only takes effect
  // when both are present, so an admin who enables a toggle but leaves the
  // value blank gets a no-op (no silent default).
  const stampLink = typography?.linkStampScale === true ? "on" : undefined;
  // Default ('drop') stays absent so legacy CSS rules apply unchanged.
  const stampShadowStyle =
    typography?.stampShadowStyle === "extruded" || typography?.stampShadowStyle === "layered"
      ? typography.stampShadowStyle
      : undefined;
  const sectionStroke =
    typography?.sectionTitleStrokeEnabled === true && typography?.sectionTitleStrokeW
      ? "on"
      : undefined;
  const sectionShadow =
    typography?.sectionTitleShadowEnabled === true && typography?.sectionTitleShadowOffset
      ? "on"
      : undefined;
  const heroStroke =
    typography?.heroTitleStrokeEnabled === true && typography?.heroTitleStrokeW
      ? "on"
      : undefined;
  const heroShadow =
    typography?.heroTitleShadowEnabled === true && typography?.heroTitleShadowOffset
      ? "on"
      : undefined;
  const subtitleStroke =
    typography?.subtitleStrokeEnabled === true && typography?.subtitleStrokeW
      ? "on"
      : undefined;
  const subtitleShadow =
    typography?.subtitleShadowEnabled === true && typography?.subtitleShadowOffset
      ? "on"
      : undefined;

  const typographyStyle: Record<string, string> = {};
  if (sectionStroke) typographyStyle["--section-title-stroke-w"] = typography!.sectionTitleStrokeW!;
  if (sectionShadow) typographyStyle["--section-title-shadow-offset"] = typography!.sectionTitleShadowOffset!;
  if (heroStroke) typographyStyle["--hero-title-stroke-w"] = typography!.heroTitleStrokeW!;
  if (heroShadow) typographyStyle["--hero-title-shadow-offset"] = typography!.heroTitleShadowOffset!;
  if (subtitleStroke) typographyStyle["--subtitle-stroke-w"] = typography!.subtitleStrokeW!;
  if (subtitleShadow) typographyStyle["--subtitle-shadow-offset"] = typography!.subtitleShadowOffset!;

  applyTextMetrics(typographyStyle, "typo-content-header", typography?.contentHeader);
  applyTextMetrics(typographyStyle, "typo-homepage-header", typography?.homepageHeader);
  applyTextMetrics(typographyStyle, "typo-subtitle", typography?.subtitle);
  applyTextMetrics(typographyStyle, "typo-body-text", typography?.bodyText);
  applyTextMetrics(typographyStyle, "typo-section-header", typography?.sectionHeader);
  applyTextMetrics(typographyStyle, "typo-text-header", typography?.textHeader);
  applyTextMetrics(typographyStyle, "typo-promo-header", typography?.promoHeader);
  applyTextMetrics(typographyStyle, "typo-teachers-header", typography?.teachersHeader);
  applyTextMetrics(typographyStyle, "typo-body", typography?.body);
  applyTextMetrics(typographyStyle, "typo-body-italic", typography?.bodyItalic);
  applyTextMetrics(typographyStyle, "typo-hero-title", typography?.heroTitle);
  applyTextMetrics(typographyStyle, "typo-nav", typography?.nav);
  applyTextMetrics(typographyStyle, "typo-meta", typography?.meta);

  // Link-mode coefficients — when set, override the legacy 0.025em / 0.0535em
  // defaults. Value is a CSS length at the 104px reference, converted to em
  // here so the same single rule in typography.css uses it without further
  // plumbing. Per-size overrides still beat these because they write
  // --stamp-stroke-em / --stamp-shadow-em directly at higher source order.
  if (typography?.linkStampStrokeWAt104) {
    typographyStyle["--link-stamp-stroke-em"] = `calc(${typography.linkStampStrokeWAt104} / 104px * 1em)`;
  }
  if (typography?.linkStampShadowOffsetAt104) {
    typographyStyle["--link-stamp-shadow-em"] = `calc(${typography.linkStampShadowOffsetAt104} / 104px * 1em)`;
  }

  // Always set --landing-design-width so both layout.css and landing-zoom.tsx
  // use the same canvas width. Defaults to 1440 (1320px content + 60px padding
  // each side). Values below 1440 are clamped because the IBC Figma artboard is
  // fixed at 1440px; e.g. 1420px would collapse the content width to 1300px.
  const landingDesignWidth =
    zoom?.designWidth && typeof zoom.designWidth === "number" && zoom.designWidth > 0
      ? Math.max(1440, zoom.designWidth)
      : 1440;
  typographyStyle["--landing-design-width"] = `${landingDesignWidth}px`;

  const htmlStyle =
    Object.keys(typographyStyle).length > 0
      ? (typographyStyle as React.CSSProperties)
      : undefined;

  const prepaintScript =
    zoom?.preventInitialFlicker === true && zoom
      ? buildPrepaintScript(zoom)
      : null;
  const typographyViewportStyle = buildTypographyViewportStyle(typography);

  return (
    <html
      lang="uk"
      className={`${fontMaru.variable} ${fontMaruOblique.variable} ${fontDisplay.variable}`}
      data-stamp-link={stampLink}
      data-stamp-shadow-style={stampShadowStyle}
      data-section-stroke={sectionStroke}
      data-section-shadow={sectionShadow}
      data-hero-stroke={heroStroke}
      data-hero-shadow={heroShadow}
      data-subtitle-stroke={subtitleStroke}
      data-subtitle-shadow={subtitleShadow}
      data-nav-underline={navUnderlineMode}
      style={htmlStyle}
    >
      <head>
        {/* Disable iOS Safari "data detectors" that auto-convert phone numbers,
            addresses, dates and emails into underlined tappable links. The
            studio address and phone in the footer/header should look like
            plain styled text unless explicitly wrapped in an <a>. */}
        <meta name="format-detection" content="telephone=no, date=no, address=no, email=no" />
        <meta name="x-apple-disable-message-reformatting" content="" />
        {prepaintScript ? (
          <script dangerouslySetInnerHTML={{ __html: prepaintScript }} />
        ) : null}
        {typographyViewportStyle ? (
          <style
            id="typography-viewport-overrides"
            dangerouslySetInnerHTML={{ __html: typographyViewportStyle }}
          />
        ) : null}
      </head>
      <body>
        {children}
        <ScrollToTop
          enabled={scrollToTop?.enabled !== false}
          right={scrollToTop?.right}
          bottom={scrollToTop?.bottom}
          showAfter={scrollToTop?.showAfter}
          stopOffset={scrollToTop?.stopOffset}
        />
      </body>
    </html>
  );
}
