import type { Metadata } from "next";
import "./globals.css";
import { fontMaru, fontMaruOblique, fontDisplay } from "./fonts";
import { ScrollToTop } from "@/components/landing/ui/scroll-to-top";
import { getSiteSettings, type ZoomSettings } from "@/lib/api-public";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Pre-paint script — emitted only when admin enables `Prevent initial
 * flicker` in Settings. Synchronously, in <head>, before first paint:
 *
 *   1. when `normalizeViewport=true` AND `normalizeViewportWidth` is set,
 *      writes <meta viewport content="width=N">;
 *   2. when `enableZoom !== false`, computes CSS `zoom` for .landing-stack
 *      and injects <style id="landing-zoom-pre"> with that value;
 *   3. when `hideScrollbar=true`, adds .hide-scrollbar to <html>.
 *
 * Critically — when normalizeViewport=true, the zoom denominator is the
 * admin-configured `normalizeViewportWidth`, NOT `document.documentElement
 * .clientWidth`. During HTML parsing of <head>, browsers do not always
 * synchronously re-evaluate a freshly written <meta viewport>, so reading
 * clientWidth there can return the device's natural width and produce a
 * different zoom value than the post-hydration LandingZoom does — which
 * IS the flicker we are trying to eliminate.
 *
 * No hardcoded fallback values: if a required admin field is missing or
 * invalid, the corresponding operation is skipped entirely.
 */
function buildPrepaintScript(zoom: ZoomSettings): string | null {
  const isPosNum = (v: unknown): v is number =>
    typeof v === "number" && isFinite(v) && v > 0;

  const enableZoom = zoom.enableZoom !== false;
  const normalizeViewport = zoom.normalizeViewport === true;
  const hideScrollbar = zoom.hideScrollbar === true;

  // Fall back to 1440 (matching the CSS --landing-design-width default) so the
  // prepaint script can apply zoom even when the admin hasn't set designWidth.
  const designWidth = isPosNum(zoom.designWidth) ? zoom.designWidth
    : zoom.enableZoom !== false ? 1440 : null;
  const zoomBreakpoint = isPosNum(zoom.zoomBreakpoint) ? zoom.zoomBreakpoint : null;
  const scale = isPosNum(zoom.scale) ? zoom.scale : null;
  const normalizeViewportWidth = isPosNum(zoom.normalizeViewportWidth)
    ? zoom.normalizeViewportWidth
    : null;

  const cfg = {
    enableZoom,
    normalizeViewport: normalizeViewport && normalizeViewportWidth != null,
    hideScrollbar,
    designWidth,
    zoomBreakpoint,
    scale,
    normalizeViewportWidth,
  };

  const noOp =
    !cfg.normalizeViewport &&
    !cfg.hideScrollbar &&
    !(cfg.enableZoom && cfg.designWidth != null);
  if (noOp) return null;

  const json = JSON.stringify(cfg).replace(/</g, "\\u003c");
  return `(function(){try{
  var s=${json};
  if(s.normalizeViewport){
    var m=document.querySelector('meta[name="viewport"]');
    if(!m){m=document.createElement('meta');m.name='viewport';document.head.appendChild(m);}
    m.content='width='+s.normalizeViewportWidth;
  }
  if(s.hideScrollbar){document.documentElement.classList.add('hide-scrollbar');}
  if(s.enableZoom&&s.designWidth){
    var basis=s.normalizeViewport?s.normalizeViewportWidth:document.documentElement.clientWidth;
    if(s.zoomBreakpoint==null||basis>=s.zoomBreakpoint){
      var f=Math.min(1,basis/s.designWidth);
      if(s.scale)f*=s.scale;
      if(f>0&&f<0.999){
        var st=document.createElement('style');
        st.id='landing-zoom-pre';
        st.textContent='.landing-stack{zoom:'+f.toFixed(5)+'}';
        document.head.appendChild(st);
      }
    }
  }
}catch(e){}})()`;
}

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const settingsRes = await getSiteSettings();
  const data = settingsRes.ok ? settingsRes.data : undefined;
  const scrollToTop = data?.scrollToTop;
  const typography = data?.typography;
  const zoom = data?.zoom;
  const header = data?.header;

  // Default mode keeps the legacy "parent only" behavior — childless top
  // items show no underline. Only `'all'` or `'none'` materialize a
  // data-attribute override on <html>; for `'parent'` we leave it absent so
  // bare CSS rules (which already encode "parent only") apply unchanged.
  const navUnderlineMode =
    header?.navUnderlineMode === "all" || header?.navUnderlineMode === "none"
      ? header.navUnderlineMode
      : undefined;

  // Per-size override flags — each pair (toggle + value) only takes effect
  // when both are present, so an admin who enables a toggle but leaves the
  // value blank gets a no-op (no silent default).
  const stampLink = typography?.linkStampScale === true ? "on" : undefined;
  // Default ('drop') stays absent so legacy CSS rules apply unchanged.
  const stampShadowStyle =
    typography?.stampShadowStyle === "extruded" ? "extruded" : undefined;
  const sectionStroke =
    typography?.sectionTitleStrokeEnabled === true && typography?.sectionTitleStrokeW
      ? "on"
      : undefined;
  const sectionShadow =
    typography?.sectionTitleShadowEnabled === true && typography?.sectionTitleShadowOffset
      ? "on"
      : undefined;
  const heroStroke =
    typography?.heroTitleStrokeEnabled === true && typography?.heroTitleStrokeW
      ? "on"
      : undefined;
  const heroShadow =
    typography?.heroTitleShadowEnabled === true && typography?.heroTitleShadowOffset
      ? "on"
      : undefined;
  const subtitleStroke =
    typography?.subtitleStrokeEnabled === true && typography?.subtitleStrokeW
      ? "on"
      : undefined;
  const subtitleShadow =
    typography?.subtitleShadowEnabled === true && typography?.subtitleShadowOffset
      ? "on"
      : undefined;

  const typographyStyle: Record<string, string> = {};
  if (sectionStroke) typographyStyle["--section-title-stroke-w"] = typography!.sectionTitleStrokeW!;
  if (sectionShadow) typographyStyle["--section-title-shadow-offset"] = typography!.sectionTitleShadowOffset!;
  if (heroStroke) typographyStyle["--hero-title-stroke-w"] = typography!.heroTitleStrokeW!;
  if (heroShadow) typographyStyle["--hero-title-shadow-offset"] = typography!.heroTitleShadowOffset!;
  if (subtitleStroke) typographyStyle["--subtitle-stroke-w"] = typography!.subtitleStrokeW!;
  if (subtitleShadow) typographyStyle["--subtitle-shadow-offset"] = typography!.subtitleShadowOffset!;

  // Link-mode coefficients — when set, override the legacy 0.025em / 0.0535em
  // defaults. Value is a CSS length at the 104px reference, converted to em
  // here so the same single rule in typography.css uses it without further
  // plumbing. Per-size overrides still beat these because they write
  // --stamp-stroke-em / --stamp-shadow-em directly at higher source order.
  if (typography?.linkStampStrokeWAt104) {
    typographyStyle["--link-stamp-stroke-em"] = `calc(${typography.linkStampStrokeWAt104} / 104px * 1em)`;
  }
  if (typography?.linkStampShadowOffsetAt104) {
    typographyStyle["--link-stamp-shadow-em"] = `calc(${typography.linkStampShadowOffsetAt104} / 104px * 1em)`;
  }

  // Always set --landing-design-width so both layout.css and landing-zoom.tsx
  // use the same canvas width. Defaults to 1440 (1320px content + 60px padding
  // each side) when the admin hasn't configured designWidth explicitly.
  const landingDesignWidth =
    zoom?.designWidth && typeof zoom.designWidth === "number" && zoom.designWidth > 0
      ? zoom.designWidth
      : 1440;
  typographyStyle["--landing-design-width"] = `${landingDesignWidth}px`;

  const htmlStyle =
    Object.keys(typographyStyle).length > 0
      ? (typographyStyle as React.CSSProperties)
      : undefined;

  const prepaintScript =
    zoom?.preventInitialFlicker === true && zoom
      ? buildPrepaintScript(zoom)
      : null;

  return (
    <html
      lang="uk"
      className={`${fontMaru.variable} ${fontMaruOblique.variable} ${fontDisplay.variable}`}
      data-stamp-link={stampLink}
      data-stamp-shadow-style={stampShadowStyle}
      data-section-stroke={sectionStroke}
      data-section-shadow={sectionShadow}
      data-hero-stroke={heroStroke}
      data-hero-shadow={heroShadow}
      data-subtitle-stroke={subtitleStroke}
      data-subtitle-shadow={subtitleShadow}
      data-nav-underline={navUnderlineMode}
      style={htmlStyle}
    >
      <head>
        {/* Disable iOS Safari "data detectors" that auto-convert phone numbers,
            addresses, dates and emails into underlined tappable links. The
            studio address and phone in the footer/header should look like
            plain styled text unless explicitly wrapped in an <a>. */}
        <meta name="format-detection" content="telephone=no, date=no, address=no, email=no" />
        <meta name="x-apple-disable-message-reformatting" content="" />
        {prepaintScript ? (
          <script dangerouslySetInnerHTML={{ __html: prepaintScript }} />
        ) : null}
      </head>
      <body>
        {children}
        <ScrollToTop
          enabled={scrollToTop?.enabled !== false}
          right={scrollToTop?.right}
          bottom={scrollToTop?.bottom}
          showAfter={scrollToTop?.showAfter}
          stopOffset={scrollToTop?.stopOffset}
        />
      </body>
    </html>
  );
}
